// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykblvrvugnqrikhloplm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrYmx2cnZ1Z25xcmlraGxvcGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MzAwNTYsImV4cCI6MjA1NTMwNjA1Nn0.ikHtBhqVjgIuDgvlRiaxb4dicw810ex_-bCBk1GMIPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);